### ISSUE TITLE
personal TODO

### ISSUE THREAD

**Issue by ThaTiemsz** [SebasJan/TheGardenGroup#25]
- [x] Move to DataGridView
- ~~Add auto incr. ID to tickets collection~~
- [x] Sort by date, status open
- [x] Add View button
- [x] View Ticket modal:
  - [x] Resolve button
  - [x] Close button
  - [x] Delete button
- [x] Link Create Incident button
- [x] Link Edit ticket button
- [x] API
- [x] Update READMEs
